//JS
import 'formdata-polyfill'
import 'jquery'
import '../../node_modules/inputmask/dist/inputmask/jquery.inputmask'
import 'popper.js'
import 'bootstrap'
import '../../vendor/yiisoft/yii2/assets/yii'
import '../../vendor/yiisoft/yii2/assets/yii.validation'
import '../../vendor/yiisoft/yii2/assets/yii.activeForm'
import '../../vendor/yiisoft/yii2/assets/yii.gridView'
import '../../vendor/bower-asset/yii2-pjax/jquery.pjax'
import './js/inspinia'
import 'metismenu'
import 'smartmenus'
import 'jquery-slimscroll'
import 'air-datepicker'
import '../src/js/pace'
import '../../node_modules/notifier-js/dist/js/notifier'

import '../src/js/select2/dist/js/select2.full'
import '../src/js/custom'
import '../src/js/reports'
import '../src/js/notifications'



//CSS
import '../../node_modules/bootstrap/dist/css/bootstrap.css'
import '../src/css/inspinia_fonts.css'
import '../../node_modules/font-awesome/css/font-awesome.css'
import '../../node_modules/animate.css/animate.css'
import '../../node_modules/metismenu/dist/metisMenu.css'
import '../../node_modules/smartmenus/dist/css/sm-core-css.css'
import '../../node_modules/smartmenus/dist/css/sm-mint/sm-mint.css'
import '../../node_modules/air-datepicker/dist/css/datepicker.min.css'
import '../src/css/style.css'
import '../src/js/select2/dist/css/select2.css'
import '../../node_modules/notifier-js/dist/css/notifier.css'
import '../src/css/custom.css'
